import { Inter } from 'next/font/google'
import './globals.css'

// components
import { ThemeProvider } from './_components/Theme-provider';
import Footer from './_components/Footer';
import Header from './_components/Header';

// configs
export const dynamic = 'force-dynamic'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
              <Header/>
              <main className='max-w-screen-xl mx-auto min-h-screen'>
                {children}
              </main>
              <Footer/>

        </ThemeProvider>
      </body>
    </html>
  )
}
