import { Inter } from 'next/font/google'
import './globals.css'

// components
import { ThemeProvider } from './_components/Theme-provider';
import Header from './_components/Header';
import MainFooter from './_components/Footer';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers'

// configs
export const dynamic = 'force-dynamic'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
const supabase = createServerComponentClient({ cookies })
const { data, error } = await supabase.auth.getSession()

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header user={data.session?.user}/>
            <main className='min-h-[80vh] max-w-[2000px] mx-auto 
              bg-gradient-to-r from-gray-200 to-slate-100  dark:from-slate-900 dark:from-10% dark:via-indigo-950 dark:via-80% dark:to-slate-800 dark:to-100% dark:text-slate-300'>
              {children}
            </main>
            <MainFooter />
        </ThemeProvider>
      </body>
    </html>
  )
}
